# NOTE: This should be a good reference for github actions w.r.t haskell
# https://markkarpov.com/post/github-actions-for-haskell-ci.html

name: cabal:build
on:
  push:
    branches:
      - main
  pull_request:
    #branches:
    #  - main
    #types:
    #  - opened
    #  - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        cabal: ["3.6", "3.10"]
        ghc: ["9.2.8", "9.4.8", "9.6.3"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Freeze
        run: |
          cabal update
          cabal configure --enable-tests --test-show-details=direct
          cabal freeze

      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-cabal
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-      

      - name: Build
        run: cabal build

      - name: Test
        run: cabal test all $CONFIG

      - name: Haddock
        run: cabal haddock all $CONFIG

      - name: SDist
        run: cabal sdist all $CONFIG
